// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
/*
class Bjorn
{
public:
		Bjorn()
			: velocity_(0),
			x_(0), y_(0)
	{}
	
	void update(World& world, Graphics& graphics);
	
private:
	
	int velocity_;
	int x_, y_;
	
	Volume volume_;
	
	Sprite spriteStand_;
	Sprite spriteWalkLeft_;
	Sprite spriteWalkRight_;
};*/
// ------------------------------------------------------------------------------
using System;
namespace GameProgrammingPatterns
{
	class Volume
	{
	}

}

