//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Patterns
{


	public interface AcmeInterface
	{
		void setFirstName(string f);
		void setLastName(String l);
		string getFirstName();
		string getLastName();
	}

	public class AcmeClass:AcmeInterface
	{
	
		private string firstName;
		private string lastName;

		public void setFirstName (string f)
		{
			firstName = f;
		}
		public void setLastName (string l)
		{
			lastName = l;
		}
		public string getFirstName ()
		{
			return firstName;
		}
		public string getLastName ()
		{
			return lastName;
		}	
	}


	public interface AceInterface
	{
		void setName(String n);
		string getName();
	}

	public class AceClass:AceInterface
	{

		private string name;
		public  AceClass()
		{

		}
		public void setName(String n)
		{
			name = n;
		}
		public string getName()
		{
			return name;
		}
	}

	public class AceToAcmeAdapter
	{
		
		private AceClass ace;
		private string firstName;
		private string lastName;

		public AceToAcmeAdapter(AceClass aceclass)
		{
			ace = aceclass;
			string[] names = ace.getName ().Split ();
			firstName=names [0];
			lastName=names [1];
		}


		public void setFirstName (string f)
		{

			firstName = f;
		}
		public void setLastName (string l)
		{
			lastName = l;
		}
		public string getFirstName ()
		{
			return firstName;
		}
		public string getLastName ()
		{
			return lastName;
		}	


	}




}

