//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Patterns
{
	public interface ICommand
	{
		void Execute();
	}
	public interface IReceiver
	{
		void connect();
		void shutdown();
		void reboot();
		void disconnect();
		void diagnostics();
	}


	public class AsiaServer:IReceiver
	{

		public AsiaServer()
		{
		}
		
		public void connect()
		{
			Console.WriteLine("You're connected to the Asia server.");
		}
		
		public void diagnostics()
		{
			Console.WriteLine("The Asia server diagnostics check out OK.");
		}
		
		public void shutdown()
		{
			Console.WriteLine("Shutting down the Asia server.");
		}
		
		public void reboot()
		{
			Console.WriteLine("Rebooting the Asia server.");
		}
		
		public void disconnect()
		{
			Console.WriteLine("You're disconnected from the Asia server.");
		}
		
	}


	public class ShutDownAsiaCommand:ICommand
	{
		IReceiver receiver;
		public ShutDownAsiaCommand(IReceiver rec)
		{
			receiver = rec;
		}

		public void Execute ()
		{
			receiver.connect();
			receiver.shutdown();
			receiver.disconnect();
		}
	}

	public class RebootCommand : ICommand
	{
		IReceiver receiver;
		
		public RebootCommand(IReceiver r)
		{
			receiver = r;
		}
		
		public void Execute()
		{
			receiver.connect();
			receiver.reboot();
			receiver.disconnect();

		}
		

	}

}

