//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Patterns
{
	public class Computer
	{
		public Computer ()
		{
		}

		public string description()
		{
			return "computer";
		}
	}


	public abstract class ComponentDecorator: Computer
	{
		public abstract new string description();
	}



	public class Disk:ComponentDecorator
	{
		Computer computer;
		public  Disk(Computer c)
		{
			computer = c;
		}

		public override string description()
		{
			return computer.description() + " and a disk";
		}
	}

}

