//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Patterns
{
	public class DifficultProduct
	{
		char[] nameChars = new char[7];
		public DifficultProduct()
		{
		}
		public void setFirstNameCharacter(char c)
		{
			nameChars[0] = c;
		}
		public void setSecondNameCharacter(char c)
		{
			nameChars[1] = c;
		}
		public void setThirdNameCharacter(char c)
		{
			nameChars[2] = c;
		}
		public void setFourthNameCharacter(char c)
		{
			nameChars[3] = c;
		}
		public void setFifthNameCharacter(char c)
		{
			nameChars[4] = c;
		}
		public void setSixthNameCharacter(char c)
		{
			nameChars[5] = c;
		}
		public void setSeventhNameCharacter(char c)
		{
			nameChars[6] = c;
		}
		public String getName()
		{
			return new String(nameChars);
		}
	}


	public class simpleProductFacade
	{
		DifficultProduct difficultProduct;
		public simpleProductFacade()
		{
			difficultProduct = new DifficultProduct ();
		}
		public string getName()
		{
			return difficultProduct.getName ();
		}
		public void setName(string name)
		{
			char[] chars = name.ToCharArray();

			if (chars.Length>0)
				difficultProduct.setFirstNameCharacter(chars[0]);
			if (chars.Length>1)
				difficultProduct.setSecondNameCharacter(chars[1]);
			if (chars.Length>2)
				difficultProduct.setThirdNameCharacter(chars[2]);
			if (chars.Length>3)
				difficultProduct.setFourthNameCharacter(chars[3]);
			if (chars.Length>4)
				difficultProduct.setFifthNameCharacter(chars[4]);
			if (chars.Length>5)
				difficultProduct.setSixthNameCharacter(chars[5]);
			if (chars.Length>6)
				difficultProduct.setSeventhNameCharacter(chars[6]);

		}
	}

}

