//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Patterns
{
	public class FirstFactory
	{
		string db;
		public FirstFactory (string name)
		{
			db = name;
		}

		public Connection CreateConnection()
		{
			if (db == "Oracle")
				return new OracleConnection ();
			else 
				return new SQLServerConnection ();
		}
	}

	public abstract class Connection
	{
		public abstract string description();
	}

	public class OracleConnection:Connection
	{
		public override string description()
		{
			return "Oracle";
		}
	}
	public class SQLServerConnection:Connection
	{
		public override string description()
		{
			return "SQL";
		}
	}
}

