//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Patterns
{
	public class Mediator
	{
		Welcome welcome;
		Shop shop;
		Purchase purchase;
		Exit exit;
		
		public Mediator()
		{
			welcome = new Welcome(this);
			shop = new Shop(this);
			purchase = new Purchase(this);
			exit = new Exit(this);
		}
		
		public void handle(String state)
		{
			if(state==("welcome.shop")){
				shop.go();
			} else if(state==("shop.purchase")){
				purchase.go();
			} else if(state==("purchase.exit")){
				exit.go();
			} else if(state==("welcome.exit")){
				exit.go();
			} else if(state==("shop.exit")){
				exit.go();
			} else if(state==("purchase.exit")){
				exit.go();
			}
		}
		
		public Welcome getWelcome()
		{
			return welcome;
		}
	}

	public class Exit
	{
		Mediator mediator;
		
		public Exit(Mediator m)
		{
			mediator = m;
		}
		
		public void go()
		{
			Console.WriteLine("Please come again sometime.");
		}
	}
	
	public class Purchase
	{
		Mediator mediator;
		String response = "n";
		
		public Purchase(Mediator m)
		{
			mediator = m;
		}
		
		public void go()
		{					
			 response = "y";
			
			if (response==("y")){
				Console.WriteLine("Thanks for your purchase.");
			}
			
			mediator.handle("purchase.exit");
		}
	}

	
	public class Shop
	{
		Mediator mediator;
		String response = "n";
		
		public Shop(Mediator m)
		{
			mediator = m;
		}
		
		public void go()
		{
			response = "y";
			
			if (response==("y")){
				mediator.handle("shop.purchase");
			} else {
				mediator.handle("shop.exit");
			}
		}
	}
	
	public class Welcome
	{
		Mediator mediator;
		String response = "n";
		
		public Welcome(Mediator m)
		{
			mediator = m;
		}
		
		public void go()
		{
			response = "y";
			
			if (response==("y")){
				mediator.handle("welcome.shop");
			} else {
				mediator.handle("welcome.exit");
			}
		}
	}


}

