//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Patterns
{
	public interface IObserver
	{
		void Update(string operation,string record);
	}

	public interface ISubject
	{
		void RegisterObserver(IObserver o);
		void RemoveObserver(IObserver o);
		void NotifyObservers();
	}

	public class Client:IObserver
	{
		public void Update(string operation,string record)
		{
			string str=string.Format("The client says a {0} operation was performed on {1}",operation,record);
			Console.WriteLine (str);
		}
	}
	public class Boss:IObserver
	{
		public void Update(string operation,string record)
		{
			string str=string.Format("The boss says a {0} operation was performed on {1}",operation,record);
			Console.WriteLine (str);
		}
	}


	public class Database:ISubject
	{
		List<IObserver> observers = new List<IObserver> ();
		private string operation;
		private string record;

		public void RegisterObserver (IObserver o)
		{
			observers.Add (o);
		}

		public void RemoveObserver (IObserver o)
		{
			observers.Remove (o);
		}

		public void NotifyObservers ()
		{
			foreach (var o in observers) {
				o.Update(operation,record);
			}
		}

		public void EditRecord(string op,string rec)
		{
					operation = op;
					record = rec;
					NotifyObservers ();
		}


	}

}

