//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Patterns
{


 	public interface IGoAlgorithm
	{
		void Go();
	}


	public class GoByDriving:IGoAlgorithm
	{
		public void Go ()
		{
			Console.WriteLine ("Go By driving");
		}
	}
	public class GoByFlyging:IGoAlgorithm
	{	
		public void Go ()
		{
			Console.WriteLine ("Go By flying");
		}	
	}


	public abstract class Vehicle
	{
		private IGoAlgorithm goAlgorithm;

		public 	Vehicle()
		{

		}

		public void SetGoAlgorithm(IGoAlgorithm goAlg)
		{
			goAlgorithm=goAlg;
		}

		public void Go()
		{
			goAlgorithm.Go ();
		}		
	}


	public class StreetRacing:Vehicle
	{		
		public  StreetRacing ()
		{
			SetGoAlgorithm (new GoByDriving ());
		}
	}

	public class Helicopter:Vehicle
	{		
		public  Helicopter ()
		{
			SetGoAlgorithm (new GoByFlyging ());
		}
	}

}

