//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

namespace EffectiveC
{
	public class PreferQuerySyntaxtoLoops
	{
		private static IEnumerable<Tuple<int, int>> ProduceIndices2()
		{
			for (int x = 0; x < 100; x++)
				for (int y = 0; y < 100; y++)
					if (x + y < 100)
						yield return Tuple.Create(x, y);
		}
		
		private static IEnumerable<Tuple<int, int>> QueryIndices2()
		{
		return from x in Enumerable.Range(0, 100)
				from y in Enumerable.Range(0, 100)
					where x + y < 100
					select Tuple.Create(x, y);

		}
	}
}

